/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiCallbacksGoogleRouteImport } from './routes/api/callbacks/google'
import { Route as AuthedUsersUserIdRouteImport } from './routes/_authed/users.$userId'
import { Route as AuthedGamesCreateRouteImport } from './routes/_authed/games.create'
import { Route as AuthedGamesGameIdManageRouteImport } from './routes/_authed/games.$gameId.manage'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCallbacksGoogleRoute = ApiCallbacksGoogleRouteImport.update({
  id: '/api/callbacks/google',
  path: '/api/callbacks/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersUserIdRoute = AuthedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGamesCreateRoute = AuthedGamesCreateRouteImport.update({
  id: '/games/create',
  path: '/games/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGamesGameIdManageRoute = AuthedGamesGameIdManageRouteImport.update({
  id: '/games/$gameId/manage',
  path: '/games/$gameId/manage',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/games/create': typeof AuthedGamesCreateRoute
  '/users/$userId': typeof AuthedUsersUserIdRoute
  '/api/callbacks/google': typeof ApiCallbacksGoogleRoute
  '/games/$gameId/manage': typeof AuthedGamesGameIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/games/create': typeof AuthedGamesCreateRoute
  '/users/$userId': typeof AuthedUsersUserIdRoute
  '/api/callbacks/google': typeof ApiCallbacksGoogleRoute
  '/games/$gameId/manage': typeof AuthedGamesGameIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/games/create': typeof AuthedGamesCreateRoute
  '/_authed/users/$userId': typeof AuthedUsersUserIdRoute
  '/api/callbacks/google': typeof ApiCallbacksGoogleRoute
  '/_authed/games/$gameId/manage': typeof AuthedGamesGameIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/games/create'
    | '/users/$userId'
    | '/api/callbacks/google'
    | '/games/$gameId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/games/create'
    | '/users/$userId'
    | '/api/callbacks/google'
    | '/games/$gameId/manage'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/games/create'
    | '/_authed/users/$userId'
    | '/api/callbacks/google'
    | '/_authed/games/$gameId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCallbacksGoogleRoute: typeof ApiCallbacksGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/callbacks/google': {
      id: '/api/callbacks/google'
      path: '/api/callbacks/google'
      fullPath: '/api/callbacks/google'
      preLoaderRoute: typeof ApiCallbacksGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users/$userId': {
      id: '/_authed/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthedUsersUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/games/create': {
      id: '/_authed/games/create'
      path: '/games/create'
      fullPath: '/games/create'
      preLoaderRoute: typeof AuthedGamesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/games/$gameId/manage': {
      id: '/_authed/games/$gameId/manage'
      path: '/games/$gameId/manage'
      fullPath: '/games/$gameId/manage'
      preLoaderRoute: typeof AuthedGamesGameIdManageRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedGamesCreateRoute: typeof AuthedGamesCreateRoute
  AuthedUsersUserIdRoute: typeof AuthedUsersUserIdRoute
  AuthedGamesGameIdManageRoute: typeof AuthedGamesGameIdManageRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedGamesCreateRoute: AuthedGamesCreateRoute,
  AuthedUsersUserIdRoute: AuthedUsersUserIdRoute,
  AuthedGamesGameIdManageRoute: AuthedGamesGameIdManageRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCallbacksGoogleRoute: ApiCallbacksGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
